export const BRAND_MARKERS = [
  "aldi",
  "ambrosia",
  "anchor",
  "angel delight",
  "asda",
  "bachelors",
  "baileys",
  "batchelors",
  "ben and jerrys",
  "benecol",
  "bernard matthews",
  "birds eye",
  "bisto",
  "bonne maman",
  "border biscuits",
  "brakes",
  "bramwells",
  "branston",
  "breyers",
  "cadbury",
  "campbells",
  "canderel",
  "cathedral city",
  "cawston press",
  "cheerios",
  "clover",
  "coca cola",
  "co op",
  "copella",
  "cornetto",
  "country life",
  "cow and gate",
  "cravendale",
  "cup a soup",
  "dairylea",
  "danio",
  "danone",
  "del monte",
  "diet coke",
  "diet pepsi",
  "dole",
  "dolmio",
  "dr oetker",
  "ellas kitchen",
  "emmental president",
  "evian",
  "fairy cakes",
  "fantastic",
  "fanta",
  "flora",
  "fray bentos",
  "freee",
  "frosties",
  "ginsters",
  "glo",
  "goodfellas",
  "great stuff",
  "greggs",
  "gu",
  "haagen dazs",
  "hain",
  "heinz",
  "hellmanns",
  "herta",
  "highland spring",
  "higgidy",
  "hobnobs",
  "iceland",
  "innocent",
  "isla negra",
  "jacobs",
  "john west",
  "jus rol",
  "kelloggs",
  "kentucky fried chicken",
  "kfc",
  "kershaws",
  "kinder",
  "kingsmill",
  "kipling",
  "kirkland",
  "knorr",
  "lactofree",
  "lakeland dairies",
  "lean cuisine",
  "lidl",
  "lipton",
  "lurpak",
  "magnum",
  "mama",
  "m and s",
  "marks and spencer",
  "marks spencer",
  "marmite",
  "mccain",
  "mcdonalds",
  "mcvities",
  "mentos",
  "merevale",
  "mikado",
  "milka",
  "mitchs kitchen",
  "montezumas",
  "morrisons",
  "mr kipling",
  "muller",
  "nature valley",
  "nescafe",
  "nesquik",
  "nestle",
  "nestea",
  "nongshim",
  "nutella",
  "oatly",
  "ocean spray",
  "oldenburger",
  "one stop",
  "oreo",
  "peperami",
  "pepsi",
  "pepsi max",
  "peroni",
  "pg tips",
  "philadelphia",
  "pilgrims choice",
  "pizza express",
  "pot noodle",
  "princes",
  "propercorn",
  "quaker",
  "quorn",
  "ribena",
  "robinsons",
  "rowntrees",
  "sainsburys",
  "sainsbury",
  "schwartz",
  "shloer",
  "silverspoon",
  "skips",
  "smarties",
  "snake river",
  "softmints",
  "solero",
  "sprite",
  "starbucks",
  "stork",
  "super noodles",
  "taylors",
  "tilda",
  "toastie",
  "toblerone",
  "typhoo",
  "tropicana",
  "tesco",
  "tesco finest",
  "tesco everyday value",
  "the collective",
  "the laughing cow",
  "trebor",
  "tyrrells",
  "uncle bens",
  "vaseline",
  "waitrose",
  "walkers",
  "warburtons",
  "weetabix",
  "weight watchers",
  "weetos",
  "western family",
  "whiskas",
  "whole earth",
  "wispa",
  "wotsits",
  "wrigleys",
  "wyke farms",
  "yeo valley",
  "yoplait",
  "yorkshire tea",
] as const;
